### ISSUE TITLE
Should 'Submit an Idea' section remains in footer.php?

### ISSUE THREAD

**Issue by man4toman** [wptrainingteam/learn-theme-beta#20]
The 'Submit an Idea' section is in footer.php file, if we include the footer.php file in new pages, it loads on them.
I think it must move from footer file.

https://github.com/wptrainingteam/learn-theme-beta/blob/master/footer.php

**Comment by JulieKuehl** [comment]
The "Submit an idea" section does not appear on every page, so yes, it should be removed from footer.php.

**Comment by JulieKuehl** [comment]
Created new issue to remove the code
https://github.com/wptrainingteam/learn-theme-beta/issues/53
