### ISSUE TITLE
Remove the "Submit an Idea" section from the footer.php file

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/learn-theme-beta#53]
We don't want the "Submit an Idea" section to appear on every page on Learn.

See discussion on https://github.com/wptrainingteam/learn-theme-beta/issues/20

**Comment by man4toman** [comment]
Based on:
https://wp.invisionapp.com/share/BNP0V7QXRF8#/screens/330323713

It must be on some but not all pages.

**Comment by jessecowens** [comment]
Resolved in #56
