### ISSUE TITLE
File Not Found : Images 

### ISSUE THREAD

**Issue by trisghosh** [wptrainingteam/learn-theme-beta#58]
Images are not found in https://learnwp.jco.dev/lesson-plan/local-install

**Comment by man4toman** [comment]
Hi @trisghosh 
This must be fix on:
https://github.com/wptrainingteam/local-install

**Comment by jessecowens** [comment]
Closing this issue, reference https://github.com/wptrainingteam/local-install/issues/10 for resolution.
